<a href="https://colab.research.google.com/github/chirag2saraiya/Image/blob/master/Copy_of_Assignment2A_2B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#2A assignment
---------------------------------------
##Backpropagation Step by Step

If you are building your own neural network, you will definitely need to understand how to train it. Backpropagation is a commonly used technique for training neural network. There are many resources explaining the technique, but this post will explain backpropagation with concrete example in a very detailed colorful steps.

#Overview:
In this post, we will build a neural network with three layers:

      1.Input layer with two inputs neurons
      2. One hidden layer with two neurons
      3. Output layer with a single neuron
      
#Weights, weights, weights:

Neural network training is about finding weights that minimize prediction error. We usually start our training with a set of randomly generated weights.Then, backpropagation is used to update the weights in an attempt to correctly map arbitrary inputs to outputs.

Our initial weights will be as following: w1 = 0.31, w2 = 0.41, w3 = 0.52, w4 = 0.6, w5 = 0.10 and w6 = 0.21

#Dataset
Our dataset has one sample with two inputs and one output.

Our single sample is as following inputs=[3, 4] and output=[1].

#Forward Pass

We will use given weights and inputs to predict the output. Inputs are multiplied by weights; the results are then passed forward to next layer.

[3,4]  x  [0.31 0.52 \ 0.41  0.6]  = [2.57 3.96] x  [0.10 \ 0.21] =1.0886


#Calculating Error

Now, it’s time to find out how our network performed by calculating the difference between the actual output and predicted one. 

Error = 1/2 x (prediction-actual)^2 

Error = 1/2 x (1-1.0886)^2 = 0.003925

#Reducing Error

Our main goal of the training is to reduce the error or the difference between prediction and actual output. Since actual output is constant, “not changing”, the only way to reduce the error is to change prediction value. 

By decomposing prediction into its basic elements we can find that weights are the variable elements affecting prediction value. In other words, in order to change prediction value, we need to change weights values.

                      prediction = out
                            
                      prediction = (h1) x w5 + (h2) x w6
                            
                      prediction =(w1 x i1 + w2 x i2) x w5 + (w3 x i1 + w4 x i4) x w6
                            

The question now is how to change\update the weights value so that the error is reduced?
The answer is Backpropagation!

#Backpropagation

Backpropagation, short for “backward propagation of errors”, is a mechanism used to update the weights using gradient descent. It calculates the gradient of the error function with respect to the neural network’s weights. The calculation proceeds backwards through the network.

Gradient descent is an iterative optimization algorithm for finding the minimum of a function; in our case we want to minimize th error function. To find a local minimum of a function using gradient descent, one takes steps proportional to the negative of the gradient of the function at the current point.

                              *Wx = Wx -a(dError/dWx)

The derivation of the error function is evaluated by applying the chain rule as following


              dError/dWx = (dError/dprediction) x (dprediction/dWx)

For example, to update w6, we take the current w6 and subtract the partial derivative of error function with respect to w6. Optionally, we multiply the derivative of the error function by a selected number to make sure that the new updated weight is minimizing the error function; this number is called learning rate.

            *W6 = W6 -a(dError/dW6)



     (dError/dw6)   = (1/2 x (prediction-actual)^2  / dprediction) x (d((w1 x i1 + w2 x i2) x w5 + (w3 x i1 + w4 x i4) x w6)/ dw6)
     
     
      (dError/dw6) = (prediction-actual)x(h2)
      
      (dError/dw6) = delta x h2
      
      
  So to update w6 we can apply the following formula

*w6 = w6 -a x (delta) x h2 

Similarly, we can derive the update formula for w5 and any other weights existing between the output and the hidden layer.

*w5  = w5 - a x (delta) x h1

We can find the update formula for the remaining weights w2, w3 and w4 in the same way.


*w6 = w6 -a x (delta) x h2 

 *w5  = w5 - a x (delta) x h1
 
 *w4  = w4 - a x (i2 x (delta)w6)
 
 *w5  = w5 - a x (i1 x (delta) w6)
 
 *w5  = w5 - a x (i2 x (delta)w5)
 
 *w5  = w5 -  a x (i1 x (delta)w5)
 
 [w1 w3 / w2 w4] =  [w1 w3 / w2 w4] - a (delta) [i1/i2]  x [w5  w6 ] 
 
 
 [w5 / w6]  = [w5 / w6] - a (delta) [h1/ h2]
 
 
#Backward Pass
 
Using derived formulas we can find the new weights.

Learning rate: is a hyperparameter which means that we need to manually guess its value.

a = 0.05

 [w5 / w6]  = [0.10/ 0.21] -  0.05 x (1.0886 -1) [2.57 / 3.96]  = [ 0.0886149/ 0.1924572 ]
 
 [w1 w3 / w2  w4] =  [0.31 0.52  /  0.41  0.6]  - 0.05 x (0.0886) x [3 /4 ] x [0.10  0.21]
 
 
[w1 w3 / w2  w4]   = [0.3088  0.5172  / 0.4082 0.5963]

Now, using the new weights we will repeat the forward passed

[3 4] [0.3088  0.5172  / 0.4082 0.5963] =     [2.55 3.93]  x  [ 0.0886149/ 0.1924572 ]= 0.98441332

We can notice that the prediction 0.98441332  is a little bit closer to actual output than the previously predicted one 1.0886. We can repeat the same process of backward and forward pass until error is close or equal to zero.



        
      

# 2B assignment




In [0]:
import numpy as np

w1 = 0.31 
w2 = 0.41 
w3 = 0.52 
w4 = 0.6 
w5 = 0.10  
w6 = 0.21

op =1
a =0.05

#input Array
ip = np.array([3,4])
print(ip)

m1 = np.array([[w1,w3],[w2,w4]])

m2 = np.array([[w5],[w6]])

print('Weight w1-w4')
print(m1)

print('Weight w5-w6')
print(m2)



#Forward Pass calculation
fp1 = np.dot(ip, m1)
fp = np.dot(fp1, m2)

print('Forward path prediction as per weight assumption = %f' % fp)

#Error Calculation

error = 0.5 * (fp - op) ** 2

print('Error = %f' % error)

#Backward Pass Calculation


h2 = np.array([[fp1[0]],[fp1[1]]])

bp1 = m2 - a * (fp-op)* h2

print('New Weight w5-w6')
print(bp1)

ip1 =np.array([[ip[0]],[ip[1]]])

m3 = np.array([w5,w6])
mt = m3[None,:]

bp2 = m1 - a * (fp-op)* np.dot(ip1, mt)
print('New Weight w1-w4')
print (bp2)

#Again Forward Propogation using new weight
print('Now, using the new weights we will repeat the forward passed')
m3 = np.dot(ip, bp2) 
fp3 = np.dot(m3, bp1)
print('New Prediction')
print (fp3)

[3 4]
Weight w1-w4
[[0.31 0.52]
 [0.41 0.6 ]]
Weight w5-w6
[[0.1 ]
 [0.21]]
Forward path prediction as per weight assumption = 1.088600
Error = 0.003925
New Weight w5-w6
[[0.0886149]
 [0.1924572]]
New Weight w1-w4
[[0.308671  0.5172091]
 [0.408228  0.5962788]]
Now, using the new weights we will repeat the forward passed
New Prediction
[0.98441332]
